### ISSUE TITLE
Investigate why mock scenarios work, 'real' iperf attacks don't

### ISSUE THREAD

**Issue by christiankiller** [blockchain-signaling-system/bloss-node#10]
**Mocking `/alarm` calls works end-to-end, meaning the whole process works seamlessly when mocking a single-domain attack (e.g. AS400 nodes attack AS600 nodes).**
(Mocking means: Just sending a fake json alarm report to `/alarm` instead of iperf'ing)

**However, as soon as we run scenario attacks, e.g. AS400 and AS500 nodes attack AS600 with actual iperf attacks, the process hangs after MITIGATION_REQ_ACCEPTED**
On some instances, `bloss-node` freezes after `/blocking` was called and the `bloss-dashboard`'s aren't updated. 

Literally the only thing that is different is that iperf is not running.

**Comment by christiankiller** [comment]
**One problem could have been identified:**
- Clicking Request Help too quickly on NEW_ALARM objects (can lead to ''failed to report attackers to blockchain'' error)

**Comment by christiankiller** [comment]
Also, bloss-core trace: 
```
Nov 19 09:44:55 controller400 env[2732]: [2018-11-19 09:44:55,405] ERROR in app: Exception on /api/v1.0/mitigate [POST]
Nov 19 09:44:55 controller400 env[2732]: Traceback (most recent call last):
Nov 19 09:44:55 controller400 env[2732]:   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
Nov 19 09:44:55 controller400 env[2732]:     response = self.full_dispatch_request()
Nov 19 09:44:55 controller400 env[2732]:   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
Nov 19 09:44:55 controller400 env[2732]:     rv = self.handle_user_exception(e)
Nov 19 09:44:55 controller400 env[2732]:   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
Nov 19 09:44:55 controller400 env[2732]:     reraise(exc_type, exc_value, tb)
Nov 19 09:44:55 controller400 env[2732]:   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
Nov 19 09:44:55 controller400 env[2732]:     rv = self.dispatch_request()
Nov 19 09:44:55 controller400 env[2732]:   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
Nov 19 09:44:55 controller400 env[2732]:     return self.view_functions[rule.endpoint](**req.view_args)
Nov 19 09:44:55 controller400 env[2732]:   File "/opt/bloss/stalk/api.py", line 58, in mitigate
Nov 19 09:44:55 controller400 env[2732]:     stalk_controller.block_attackers(attack_report)
Nov 19 09:44:55 controller400 env[2732]:   File "/opt/bloss/stalk/controller.py", line 142, in block_attackers
Nov 19 09:44:55 controller400 env[2732]:     json=json.dumps(hash_to_block))
Nov 19 09:44:55 controller400 env[2732]:   File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 112, in post
Nov 19 09:44:55 controller400 env[2732]:     return request('post', url, data=data, json=json, **kwargs)
Nov 19 09:44:55 controller400 env[2732]:   File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 58, in request
Nov 19 09:44:55 controller400 env[2732]:     return session.request(method=method, url=url, **kwargs)
Nov 19 09:44:55 controller400 env[2732]:   File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 508, in request
Nov 19 09:44:55 controller400 env[2732]:     resp = self.send(prep, **send_kwargs)
Nov 19 09:44:55 controller400 env[2732]:   File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 618, in send
Nov 19 09:44:55 controller400 env[2732]:     r = adapter.send(request, **kwargs)
Nov 19 09:44:55 controller400 env[2732]:   File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 490, in send
Nov 19 09:44:55 controller400 env[2732]:     raise ConnectionError(err, request=request)
Nov 19 09:44:55 controller400 env[2732]: ConnectionError: ('Connection aborted.', BadStatusLine("''",))
```
