### ISSUE TITLE
Adapt code for multi-controller deployment

### ISSUE THREAD

**Issue by christiankiller** [blockchain-signaling-system/bloss-node#7]
- [x] Add all IP addresses and configuration-relevant variables to .env and 
- [x] Filter reports and only send via websocket the ones that contain attackers from respective subnetwork, use `SUBNETWORK` variable for that.

**Comment by christiankiller** [comment]
Especially important because of attack-report distribution. 
We don't want attack reports for c500 at c400, just causes exceptions such as this: 

```
Nov 08 21:20:08 controller400 env[1188]: {"hash": 986542956, "target": "192.168.60.5", "timestamp": "2018-11-08-20:16:46", "action": "blackhole", "subnetwork": "192.168.50.0/24", "addresses": ["192.168.50.2", "192.168.50.3", "192.168.50.4", "192.168.50.5"]}
Nov 08 21:20:08 controller400 env[1188]: [STALK/mitigate]attack_report = (attack_reporting.parse_attack_report_message(json_data))
Nov 08 21:20:08 controller400 env[1188]: {"hash": 986542956, "target": "192.168.60.5", "timestamp": "2018-11-08-20:16:46", "action": "blackhole", "subnetwork": "192.168.50.0/24", "addresses": ["192.168.50.2", "192.168.50.3", "192.168.50.4", "192.168.50.5"]}
Nov 08 21:20:08 controller400 env[1188]: [STALK/mitigate]attack_report:
Nov 08 21:20:08 controller400 env[1188]: [2018-11-08 21:20:08,633] ERROR in app: Exception on /api/v1.0/mitigate [POST]
Nov 08 21:20:08 controller400 env[1188]: Traceback (most recent call last):
Nov 08 21:20:08 controller400 env[1188]:   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
Nov 08 21:20:08 controller400 env[1188]:     response = self.full_dispatch_request()
Nov 08 21:20:08 controller400 env[1188]:   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
Nov 08 21:20:08 controller400 env[1188]:     rv = self.handle_user_exception(e)
Nov 08 21:20:08 controller400 env[1188]:   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
Nov 08 21:20:08 controller400 env[1188]:     reraise(exc_type, exc_value, tb)
Nov 08 21:20:08 controller400 env[1188]:   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
Nov 08 21:20:08 controller400 env[1188]:     rv = self.dispatch_request()
Nov 08 21:20:08 controller400 env[1188]:   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
Nov 08 21:20:08 controller400 env[1188]:     return self.view_functions[rule.endpoint](**req.view_args)
Nov 08 21:20:08 controller400 env[1188]:   File "/opt/bloss/stalk/api.py", line 58, in mitigate
Nov 08 21:20:08 controller400 env[1188]:     stalk_controller.block_attackers(attack_report)
Nov 08 21:20:08 controller400 env[1188]:   File "/opt/bloss/stalk/controller.py", line 100, in block_attackers
Nov 08 21:20:08 controller400 env[1188]:     datapath = self.get_datapath(attacker.datapath_id)
Nov 08 21:20:08 controller400 env[1188]: AttributeError: 'NoneType' object has no attribute 'datapath_id'
Nov 08 21:20:15 controller400 env[1188]: [STALK/mitigate (first try block) request.json
```
